apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-calculator-frontend
  labels:
    app: change-calculator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-calculator-frontend
  template:
    metadata:
      labels:
        app: change-calculator-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jorismathijssen/change-calculator-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: change-calculator-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
