name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set Image Names
      run: |
        echo "FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/frontend:latest" >> $GITHUB_ENV
        echo "BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/backend:latest" >> $GITHUB_ENV

    # Build and push the frontend (React + Nginx)
    - name: Build Frontend Docker Image
      run: docker build -t ${{ env.FRONTEND_IMAGE }} ./Frontend
    
    - name: Build Backend Docker Image
      run: docker build -t ${{ env.BACKEND_IMAGE }} ./Backend

    # Build and push the backend (Spring Boot + Java)
    - name: Build Backend Docker Image
      run: docker build -t ${{ env.BACKEND_IMAGE }} ./backend

    - name: Push Backend Docker Image
      run: docker push ${{ env.BACKEND_IMAGE }}
